import React from "react";
import Image from "next/legacy/image";
import {about,experience,education} from "../../constant"
import AnimatedText from "../components/AnimatedText/AnimatedText";
import AnimatedNumbers from "../components/AnimatedNumbers/AnimatedNumbers";
import Layouts from "../components/Layout/Layouts";
import profilePic from "../../public/images/profile/developer-pic-2.jpg";
import Skills from "../components/Skills/Skills";
import Experience from "../components/Experience/Experience";
import Education from "../components/Education/Education";


export const metadata = {
  title: " Waquar Mahboob | About Page",
  description: "Generated by create next app",
};

const page = () => {
  return (
      <main className="flex w-full flex-col items-center justify-center dark:text-light">
        <Layouts className="pt-16">
          <AnimatedText text={about.animatedText} className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />
          <div className="grid w-full grid-cols-8 gap-16 sm:gap-8">
            <div className="col-span-3 flex flex-col items-start justify-start xl:col-span-4 md:order-2 md:col-span-8">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75 dark:text-light/75">
                {about.heading}
              </h2>
              <p className="font-medium">
                {about.text1}
                </p>
                <p className="my-4 font-medium">
                {about.text2}{" "}
                </p>
                <p className="font-medium">
                {about.text3}
                
              </p>
              
            </div>
            <div className='col-span-3 relative h-max rounded-2xl border-2 border-solid border-dark bg-light p-8 dark:bg-dark dark:border-light xl:col-span-4 md:col-span-8 md:order-1'>
              <div className="absolute top-0 -right-3 -z-10 w-[102%] h-[103%] rounded-[2rem] bg-dark dark:bg-light"/>
              <Image priority src={profilePic} alt="Waquar Mahboob" className="w-full h-auto rounded-2xl"  
               sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw" />
            </div>
            <div className="col-span-2 flex flex-col items-end justify-between xl:col-span-8 xl:flex-row xl:items-center md:order-3">
            <div className="flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumbers value={2}/>+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">{about.experienceText}</h2>
              </div>
              <div className="flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                <AnimatedNumbers value={4}/>+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">{about.projectstext}</h2>
              </div>
              <div className="flex flex-col items-end justify-center xl:items-center">
                <span className="inline-block text-7xl font-bold md:text-6xl sm:text-5xl xs:text-4xl">
                  <AnimatedNumbers value={5}/>+
                </span>
                <h2 className="text-xl font-medium capitalize text-dark/75 dark:text-light/75 xl:text-center md:text-lg sm:text-base xs:text-sm">{about.skillsText}</h2>
              </div>
            </div>
          </div>
          <Skills/>
          <Experience experience={experience}/>
          <Education education={education}/>
        </Layouts>
      </main>
  );
};

export default page;
