import React from "react";
import AnimatedText from "../components/AnimatedText/AnimatedText";
import Layouts from "../components/Layout/Layouts";

export const metadata = {
  title: " Waquar Mahboob | About Page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <>
      <main className="flex w-full flex-col items-center justify-center ">
        <Layouts className="pt-16">
          <AnimatedText text="Passion Fuels Purpose!" className="mb-16" />
          <div className="grid w-full grid-cols-8 gap-16">
            <div className="col-span-3 flex flex-col items-start justify-start">
              <h2 className="mb-4 text-lg font-bold uppercase text-dark/75">
                Biography
              </h2>
              <p className="font-medium">
                Hi, I'm Waquar Mahboob, a web developer with a
                passion for creating beautiful, functional, and user-centered
                digital experiences. With 2 years and 7 months of experience in the field. I
                am always looking for new and innovative ways to bring my
                clients' visions to life.
                </p>
                <p className="my-4 font-medium">
                  I believe that design is about more than just making things
                  look pretty – it's about solving problems and creating
                  intuitive, enjoyable experiences for users.{" "}
                </p>
                <p className="font-medium">
                  Whether I'm working on a website, mobile app, or other digital
                  product, I bring my commitment to design excellence and
                  user-centered thinking to every project I work on. I look
                  forward to the opportunity to bring my skills and passion to
                  your next project.
                
              </p>
              
            </div>
          </div>
        </Layouts>
      </main>
    </>
  );
};

export default page;
