import React from "react";
import Layouts from "../components/Layout/Layouts";
import AnimatedText from "../components/AnimatedText/AnimatedText";
import FeaturedProject from "../components/Project/FeaturedProject";
import Project from "../components/Project/Project";
import {projects} from "../../constant"

export const metadata = {
  title: "Waquar Mahboob | Projects Page",
  description: "Generated by create next app",
};

const page = () => {
  return (
    <main className="w-full mb-16 flex flex-col items-center justify-center dark:text-light">
      <Layouts className="pt-16">
        <AnimatedText text={projects.animatedText} className="mb-16 lg:!text-7xl sm:!text-6xl xs:!text-4xl sm:mb-8" />
        <div className="grid grid-cols-12 gap-24 gap-y-32 xl:gap-x-16 lg:gap-x-8 md:gap-y-24 sm:gap-x-0">
          {projects?.data?.map((elem, ind) =>
            elem.type == "Featured Project" ? (
              <div className="col-span-12" key={ind}>
                <FeaturedProject
                  key={ind}
                  title={elem.title}
                  skills={elem.skills}
                  summary={elem.summary}
                  link={elem.link}
                  type={elem.type}
                  img={elem.img[Object.keys(elem.img)[0]]}
                  github={elem.github}
                />
              </div>
            ) : (
              <div className="col-span-6 sm:col-span-12" key={ind}>
                <Project
                key={ind}
                  title={elem.title}
                  link={elem.link}
                  type={elem.type}
                  img={elem.img[Object.keys(elem.img)[0]]}
                  github={elem.github}
                />
              </div>
            )
          )}
          
        </div>
      </Layouts>
    </main>
  );
};

export default page;
