import React from 'react'

export const metadata = {
  
  title:'Waquar Mahboob | Projects Page',
  description: 'Generated by create next app',
}
const page = () => {
  return (
    <div>
      projects
    </div>
  )
}

export default page
