import React from 'react'

export const metadata = {
  
    title:'Waquar Mahboob | Articles Page',
    description: 'Generated by create next app',
  }

const page = () => {
  return (
    <div>
      
    </div>
  )
}

export default page
